exports.campus = [
  {
    id: "78",
    pid: null,
    schpid: "NFS/837522",
    campusname: "New Fountain Secondary School",
    campusid: "NFSS",
    campusphone: "08033463927, 08050856386",
    campusemail: "info@newfountainschools.com.ng, newfountainschools@gmail.com",
    campusaddress: "Plot 2006 Block 18 Amuwo Odofin GRA \r\nBy Apple Junction.",
    campusstate: "Lagos",
    campuscountry: null,
  },
  {
    id: "79",
    pid: null,
    schpid: "NFS/837522",
    campusname: "New Fountain Montessori Children School",
    campusid: "NFMCS",
    campusphone: "08029182955, 08023211746",
    campusemail: "info@newfountainschools.com.ng",
    campusaddress: "Plot 134 Amuwo Odofin GRA\r\nBy Festac Link Bridge",
    campusstate: "Lagos",
    campuscountry: null,
  },
];
