exports.departments = [
  {
    id: "304",
    pid: null,
    schpid: "SCHMATE/732207",
    campus: "Early Spring Elementary School",
    name: "Admin",
    departid: null,
    hod: null,
  },
  {
    id: "305",
    pid: null,
    schpid: "SCHMATE/732207",
    campus: "Early Spring Nursery School",
    name: "Admin",
    departid: null,
    hod: null,
  },
  {
    id: "306",
    pid: null,
    schpid: "SCHMATE/732207",
    campus: "Early Spring College",
    name: "Admin",
    departid: null,
    hod: null,
  },
  {
    id: "307",
    pid: "923930",
    schpid: "SCHMATE/732207",
    campus: "Early Spring Elementary School",
    name: "Teaching Staff",
    departid: "TSF001",
    hod: null,
  },
  {
    id: "308",
    pid: "983143",
    schpid: "SCHMATE/732207",
    campus: "Early Spring Elementary School",
    name: "None Teaching Staff",
    departid: "NTSF002",
    hod: null,
  },
  {
    id: "309",
    pid: "565715",
    schpid: "SCHMATE/732207",
    campus: "Early Spring Elementary School",
    name: "Account",
    departid: "ACCT003",
    hod: null,
  },
  {
    id: "310",
    pid: "636494",
    schpid: "SCHMATE/732207",
    campus: "Early Spring Elementary School",
    name: "Transport",
    departid: "TSP004",
    hod: null,
  },
  {
    id: "311",
    pid: "987755",
    schpid: "SCHMATE/732207",
    campus: "Early Spring College",
    name: "Teaching Staff",
    departid: "TSF001",
    hod: null,
  },
  {
    id: "312",
    pid: "40947",
    schpid: "SCHMATE/732207",
    campus: "Early Spring College",
    name: "None Teaching Staff",
    departid: "NTSF002",
    hod: null,
  },
  {
    id: "313",
    pid: "42960",
    schpid: "SCHMATE/732207",
    campus: "Early Spring College",
    name: "Account",
    departid: "ACCT003",
    hod: null,
  },
  {
    id: "314",
    pid: "657808",
    schpid: "SCHMATE/732207",
    campus: "Early Spring College",
    name: "Transport",
    departid: "TSP004",
    hod: null,
  },
  {
    id: "315",
    pid: "979575",
    schpid: "SCHMATE/732207",
    campus: "Early Spring Nursery School",
    name: "Teaching Staff",
    departid: "TSF001",
    hod: null,
  },
  {
    id: "316",
    pid: "759400",
    schpid: "SCHMATE/732207",
    campus: "Early Spring Nursery School",
    name: "None Teaching Staff",
    departid: "NTSF002",
    hod: null,
  },
  {
    id: "317",
    pid: "533924",
    schpid: "SCHMATE/732207",
    campus: "Early Spring Nursery School",
    name: "Account",
    departid: "ACT003",
    hod: null,
  },
  {
    id: "318",
    pid: "793159",
    schpid: "SCHMATE/732207",
    campus: "Early Spring Nursery School",
    name: " Transport",
    departid: "TSP004",
    hod: null,
  },
  {
    id: "319",
    pid: "775380",
    schpid: "SCHMATE/732207",
    campus: "Early Spring Nursery School",
    name: "FOUNDATION",
    departid: "NURSERY",
    hod: null,
  },
];
