exports.nStaffs = [
  {
    id: "1",
    sch_id: "SCHMATE/732207",
    campus: "Early Spring Schools",
    designation_id: "6",
    department: "aa",
    surname: "Earlyspring",
    firstname: "Superadmin",
    middlename: "aa",
    username: "info@earlyspringschools.com",
    email: "info@earlyspringschools.com",
    phoneno: "2348165777979",
    address: "aa",
    image: null,
    class_assigned: null,
    sub_class: null,
    signature: null,
    password: "$2y$10$gU7567xqkoyZW1.mkPcWie116aI0Cnu.dM4hQ9Cl31ad3V1Pi8xPy",
    pass_word: "12345678",
    status: "Active",
    created_at: null,
    updated_at: null,
  },
  {
    id: "2",
    sch_id: "SCHMATE/732207",
    campus: "Early Spring Elementary School",
    designation_id: "1",
    department: "Admin",
    surname: "Elementary",
    firstname: "Admin",
    middlename: "",
    username: "info@earlyspringschools.com",
    email: "info@earlyspringschools.com",
    phoneno: "2348165777979",
    address: "",
    image: null,
    class_assigned: null,
    sub_class: null,
    signature: null,
    password: "$2y$10$gU7567xqkoyZW1.mkPcWie116aI0Cnu.dM4hQ9Cl31ad3V1Pi8xPy",
    pass_word: "12345678",
    status: "Active",
    created_at: null,
    updated_at: null,
  },
  {
    id: "3",
    sch_id: "SCHMATE/732207",
    campus: "Early Spring Elementary School",
    designation_id: "4",
    department: "",
    surname: "Okoro",
    firstname: "Monday",
    middlename: "John",
    username: "okoromonday22@gmail.com",
    email: "okoromonday22@gmail.com",
    phoneno: "8033403164",
    address: "",
    image: null,
    class_assigned: null,
    sub_class: null,
    signature: null,
    password: "$2y$10$gU7567xqkoyZW1.mkPcWie116aI0Cnu.dM4hQ9Cl31ad3V1Pi8xPy",
    pass_word: "12345678",
    status: "Active",
    created_at: null,
    updated_at: null,
  },
  {
    id: "4",
    sch_id: "SCHMATE/732207",
    campus: "Early Spring Elementary School",
    designation_id: "1",
    department: "",
    surname: "Borisade Odedina",
    firstname: "Temitope",
    middlename: "Oludara",
    username: "",
    email: "",
    phoneno: "8069396888",
    address: "",
    image: null,
    class_assigned: null,
    sub_class: null,
    signature: null,
    password: "$2y$10$gU7567xqkoyZW1.mkPcWie116aI0Cnu.dM4hQ9Cl31ad3V1Pi8xPy",
    pass_word: "12345678",
    status: "Active",
    created_at: null,
    updated_at: null,
  },
  {
    id: "5",
    sch_id: "SCHMATE/732207",
    campus: "Early Spring Elementary School",
    designation_id: "4",
    department: "",
    surname: "KUAM",
    firstname: "HILAIRE",
    middlename: "",
    username: "kuamhilaire@gmail.com",
    email: "kuamhilaire@gmail.com",
    phoneno: "8065509753",
    address: "",
    image: null,
    class_assigned: null,
    sub_class: null,
    signature: null,
    password: "$2y$10$gU7567xqkoyZW1.mkPcWie116aI0Cnu.dM4hQ9Cl31ad3V1Pi8xPy",
    pass_word: "12345678",
    status: "Active",
    created_at: null,
    updated_at: null,
  },
  {
    id: "6",
    sch_id: "SCHMATE/732207",
    campus: "Early Spring Elementary School",
    designation_id: "4",
    department: "",
    surname: "Alabi",
    firstname: "Timothy",
    middlename: "Oladapo",
    username: "",
    email: "",
    phoneno: "7031561337",
    address: "",
    image: null,
    class_assigned: null,
    sub_class: null,
    signature: null,
    password: "$2y$10$gU7567xqkoyZW1.mkPcWie116aI0Cnu.dM4hQ9Cl31ad3V1Pi8xPy",
    pass_word: "12345678",
    status: "Active",
    created_at: null,
    updated_at: null,
  },
  {
    id: "7",
    sch_id: "SCHMATE/732207",
    campus: "Early Spring Elementary School",
    designation_id: "4",
    department: "",
    surname: "OKERENTA",
    firstname: "CHIBUZOR",
    middlename: "GLORIA",
    username: "",
    email: "",
    phoneno: "8060242664",
    address: "",
    image: null,
    class_assigned: null,
    sub_class: null,
    signature: null,
    password: "$2y$10$gU7567xqkoyZW1.mkPcWie116aI0Cnu.dM4hQ9Cl31ad3V1Pi8xPy",
    pass_word: "12345678",
    status: "Active",
    created_at: null,
    updated_at: null,
  },
  {
    id: "8",
    sch_id: "SCHMATE/732207",
    campus: "Early Spring Elementary School",
    designation_id: "4",
    department: "",
    surname: "Nwobi",
    firstname: "Chinemelum",
    middlename: "Jessica",
    username: "",
    email: "",
    phoneno: "8068936498",
    address: "",
    image: null,
    class_assigned: null,
    sub_class: null,
    signature: null,
    password: "$2y$10$gU7567xqkoyZW1.mkPcWie116aI0Cnu.dM4hQ9Cl31ad3V1Pi8xPy",
    pass_word: "12345678",
    status: "Active",
    created_at: null,
    updated_at: null,
  },
  {
    id: "9",
    sch_id: "SCHMATE/732207",
    campus: "Early Spring Elementary School",
    designation_id: "4",
    department: "",
    surname: "NWAEDOZIE",
    firstname: "JOY",
    middlename: "ANWULI",
    username: "",
    email: "",
    phoneno: "8035191473",
    address: "",
    image: null,
    class_assigned: null,
    sub_class: null,
    signature: null,
    password: "$2y$10$gU7567xqkoyZW1.mkPcWie116aI0Cnu.dM4hQ9Cl31ad3V1Pi8xPy",
    pass_word: "12345678",
    status: "Active",
    created_at: null,
    updated_at: null,
  },
  {
    id: "10",
    sch_id: "SCHMATE/732207",
    campus: "Early Spring Elementary School",
    designation_id: "4",
    department: "",
    surname: "NZEKWE",
    firstname: "IJEOMA",
    middlename: "ELIZABETH",
    username: "bethijay@gmail.com",
    email: "bethijay@gmail.com",
    phoneno: "8033358569",
    address: "",
    image: null,
    class_assigned: null,
    sub_class: null,
    signature: null,
    password: "$2y$10$gU7567xqkoyZW1.mkPcWie116aI0Cnu.dM4hQ9Cl31ad3V1Pi8xPy",
    pass_word: "12345678",
    status: "Active",
    created_at: null,
    updated_at: null,
  },
  {
    id: "11",
    sch_id: "SCHMATE/732207",
    campus: "Early Spring Elementary School",
    designation_id: "4",
    department: "",
    surname: "Nwaisoma",
    firstname: "Merit",
    middlename: "Nneka",
    username: "",
    email: "",
    phoneno: "8036058571",
    address: "",
    image: null,
    class_assigned: null,
    sub_class: null,
    signature: null,
    password: "$2y$10$gU7567xqkoyZW1.mkPcWie116aI0Cnu.dM4hQ9Cl31ad3V1Pi8xPy",
    pass_word: "12345678",
    status: "Active",
    created_at: null,
    updated_at: null,
  },
  {
    id: "12",
    sch_id: "SCHMATE/732207",
    campus: "Early Spring Elementary School",
    designation_id: "4",
    department: "",
    surname: "Fadairo",
    firstname: "Bunmi",
    middlename: "Grace",
    username: "",
    email: "",
    phoneno: "8032272971",
    address: "",
    image: null,
    class_assigned: null,
    sub_class: null,
    signature: null,
    password: "$2y$10$gU7567xqkoyZW1.mkPcWie116aI0Cnu.dM4hQ9Cl31ad3V1Pi8xPy",
    pass_word: "12345678",
    status: "Active",
    created_at: null,
    updated_at: null,
  },
  {
    id: "13",
    sch_id: "SCHMATE/732207",
    campus: "Early Spring Elementary School",
    designation_id: "4",
    department: "",
    surname: "Wilson",
    firstname: "Moses",
    middlename: "Thompson",
    username: "mrejoice18@gmail.com",
    email: "mrejoice18@gmail.com",
    phoneno: "7067869918",
    address: "",
    image: null,
    class_assigned: null,
    sub_class: null,
    signature: null,
    password: "$2y$10$gU7567xqkoyZW1.mkPcWie116aI0Cnu.dM4hQ9Cl31ad3V1Pi8xPy",
    pass_word: "12345678",
    status: "Active",
    created_at: null,
    updated_at: null,
  },
  {
    id: "14",
    sch_id: "SCHMATE/732207",
    campus: "Early Spring Elementary School",
    designation_id: "4",
    department: "",
    surname: "Chukwuka",
    firstname: "Obianuju",
    middlename: "Peace",
    username: "",
    email: "",
    phoneno: "7019976250",
    address: "",
    image: null,
    class_assigned: null,
    sub_class: null,
    signature: null,
    password: "$2y$10$gU7567xqkoyZW1.mkPcWie116aI0Cnu.dM4hQ9Cl31ad3V1Pi8xPy",
    pass_word: "12345678",
    status: "Active",
    created_at: null,
    updated_at: null,
  },
  {
    id: "15",
    sch_id: "SCHMATE/732207",
    campus: "Early Spring Elementary School",
    designation_id: "4",
    department: "",
    surname: "Onuoha",
    firstname: "Chinyere",
    middlename: "Onyinyechi",
    username: "",
    email: "",
    phoneno: "9931368075",
    address: "",
    image: null,
    class_assigned: null,
    sub_class: null,
    signature: null,
    password: "$2y$10$gU7567xqkoyZW1.mkPcWie116aI0Cnu.dM4hQ9Cl31ad3V1Pi8xPy",
    pass_word: "12345678",
    status: "Active",
    created_at: null,
    updated_at: null,
  },
  {
    id: "16",
    sch_id: "SCHMATE/732207",
    campus: "Early Spring Elementary School",
    designation_id: "4",
    department: "",
    surname: "Osadume",
    firstname: "Emmanuel",
    middlename: "Uzochukwu",
    username: "osasefb14@gmail",
    email: "osasefb14@gmail",
    phoneno: "8984879898",
    address: "",
    image: null,
    class_assigned: null,
    sub_class: null,
    signature: null,
    password: "$2y$10$gU7567xqkoyZW1.mkPcWie116aI0Cnu.dM4hQ9Cl31ad3V1Pi8xPy",
    pass_word: "12345678",
    status: "Active",
    created_at: null,
    updated_at: null,
  },
  {
    id: "17",
    sch_id: "SCHMATE/732207",
    campus: "Early Spring Elementary School",
    designation_id: "4",
    department: "",
    surname: "Ogar",
    firstname: "Anni",
    middlename: "Ekor",
    username: "",
    email: "",
    phoneno: "8169033499",
    address: "",
    image: null,
    class_assigned: null,
    sub_class: null,
    signature: null,
    password: "$2y$10$gU7567xqkoyZW1.mkPcWie116aI0Cnu.dM4hQ9Cl31ad3V1Pi8xPy",
    pass_word: "12345678",
    status: "Active",
    created_at: null,
    updated_at: null,
  },
  {
    id: "18",
    sch_id: "SCHMATE/732207",
    campus: "Early Spring Elementary School",
    designation_id: "4",
    department: "",
    surname: "Kalu",
    firstname: "Joy",
    middlename: "",
    username: "",
    email: "",
    phoneno: "8186428582",
    address: "",
    image: null,
    class_assigned: null,
    sub_class: null,
    signature: null,
    password: "$2y$10$gU7567xqkoyZW1.mkPcWie116aI0Cnu.dM4hQ9Cl31ad3V1Pi8xPy",
    pass_word: "12345678",
    status: "Active",
    created_at: null,
    updated_at: null,
  },
  {
    id: "19",
    sch_id: "SCHMATE/732207",
    campus: "Early Spring Elementary School",
    designation_id: "4",
    department: "",
    surname: "Nwafor",
    firstname: "Chidimma",
    middlename: "Ogechukwu",
    username: "",
    email: "",
    phoneno: "8065832241",
    address: "",
    image: null,
    class_assigned: null,
    sub_class: null,
    signature: null,
    password: "$2y$10$gU7567xqkoyZW1.mkPcWie116aI0Cnu.dM4hQ9Cl31ad3V1Pi8xPy",
    pass_word: "12345678",
    status: "Disabled",
    created_at: null,
    updated_at: null,
  },
  {
    id: "20",
    sch_id: "SCHMATE/732207",
    campus: "Early Spring Elementary School",
    designation_id: "4",
    department: "",
    surname: "Uzoh",
    firstname: "Afoma",
    middlename: "T.",
    username: "tinaafy@gmail.com",
    email: "tinaafy@gmail.com",
    phoneno: "8051224643",
    address: "",
    image: null,
    class_assigned: null,
    sub_class: null,
    signature: null,
    password: "$2y$10$gU7567xqkoyZW1.mkPcWie116aI0Cnu.dM4hQ9Cl31ad3V1Pi8xPy",
    pass_word: "12345678",
    status: "Active",
    created_at: null,
    updated_at: null,
  },
  {
    id: "21",
    sch_id: "SCHMATE/732207",
    campus: "Early Spring Elementary School",
    designation_id: "4",
    department: "",
    surname: "Simeon",
    firstname: "Emmanuel",
    middlename: "Orji",
    username: "",
    email: "",
    phoneno: "7081492183",
    address: "",
    image: null,
    class_assigned: null,
    sub_class: null,
    signature: null,
    password: "$2y$10$gU7567xqkoyZW1.mkPcWie116aI0Cnu.dM4hQ9Cl31ad3V1Pi8xPy",
    pass_word: "12345678",
    status: "Active",
    created_at: null,
    updated_at: null,
  },
  {
    id: "22",
    sch_id: "SCHMATE/732207",
    campus: "Early Spring Elementary School",
    designation_id: "4",
    department: "",
    surname: "Ekpenyong",
    firstname: "John",
    middlename: "Ubong",
    username: "jekpenyong4@gmail.com",
    email: "jekpenyong4@gmail.com",
    phoneno: "8062246130",
    address: "",
    image: null,
    class_assigned: null,
    sub_class: null,
    signature: null,
    password: "$2y$10$gU7567xqkoyZW1.mkPcWie116aI0Cnu.dM4hQ9Cl31ad3V1Pi8xPy",
    pass_word: "12345678",
    status: "Active",
    created_at: null,
    updated_at: null,
  },
  {
    id: "23",
    sch_id: "SCHMATE/732207",
    campus: "Early Spring Elementary School",
    designation_id: "4",
    department: "",
    surname: "Chigoziri Nwanja",
    firstname: "Ezinne",
    middlename: "Cynthia",
    username: "Ezinnechigo@gmail.com",
    email: "Ezinnechigo@gmail.com",
    phoneno: "2348036264355",
    address: "",
    image: null,
    class_assigned: null,
    sub_class: null,
    signature: null,
    password: "$2y$10$gU7567xqkoyZW1.mkPcWie116aI0Cnu.dM4hQ9Cl31ad3V1Pi8xPy",
    pass_word: "12345678",
    status: "Active",
    created_at: null,
    updated_at: null,
  },
  {
    id: "24",
    sch_id: "SCHMATE/732207",
    campus: "Early Spring Elementary School",
    designation_id: "4",
    department: "",
    surname: "Okoroafor",
    firstname: "Chika",
    middlename: "Geraldine",
    username: "",
    email: "",
    phoneno: "8109327378",
    address: "",
    image: null,
    class_assigned: null,
    sub_class: null,
    signature: null,
    password: "$2y$10$gU7567xqkoyZW1.mkPcWie116aI0Cnu.dM4hQ9Cl31ad3V1Pi8xPy",
    pass_word: "12345678",
    status: "Active",
    created_at: null,
    updated_at: null,
  },
  {
    id: "25",
    sch_id: "SCHMATE/732207",
    campus: "Early Spring Elementary School",
    designation_id: "4",
    department: "",
    surname: "Adibeli",
    firstname: "Onyinyechukwu",
    middlename: "Stella",
    username: "adibelistella@gmail.com",
    email: "adibelistella@gmail.com",
    phoneno: "8064852920",
    address: "",
    image: null,
    class_assigned: null,
    sub_class: null,
    signature: null,
    password: "$2y$10$gU7567xqkoyZW1.mkPcWie116aI0Cnu.dM4hQ9Cl31ad3V1Pi8xPy",
    pass_word: "12345678",
    status: "Active",
    created_at: null,
    updated_at: null,
  },
  {
    id: "26",
    sch_id: "SCHMATE/732207",
    campus: "Early Spring Elementary School",
    designation_id: "4",
    department: "",
    surname: "Madumelu",
    firstname: "Chika",
    middlename: "Lilian",
    username: "",
    email: "",
    phoneno: "7034538124",
    address: "",
    image: null,
    class_assigned: null,
    sub_class: null,
    signature: null,
    password: "$2y$10$gU7567xqkoyZW1.mkPcWie116aI0Cnu.dM4hQ9Cl31ad3V1Pi8xPy",
    pass_word: "12345678",
    status: "Active",
    created_at: null,
    updated_at: null,
  },
  {
    id: "27",
    sch_id: "SCHMATE/732207",
    campus: "Early Spring Elementary School",
    designation_id: "4",
    department: "",
    surname: "Uzochukwu",
    firstname: "Chioma",
    middlename: "Ukamaka",
    username: "chiomsuk@gmail.com",
    email: "chiomsuk@gmail.com",
    phoneno: "8038907220",
    address: "",
    image: null,
    class_assigned: null,
    sub_class: null,
    signature: null,
    password: "$2y$10$gU7567xqkoyZW1.mkPcWie116aI0Cnu.dM4hQ9Cl31ad3V1Pi8xPy",
    pass_word: "12345678",
    status: "Active",
    created_at: null,
    updated_at: null,
  },
  {
    id: "28",
    sch_id: "SCHMATE/732207",
    campus: "Early Spring Elementary School",
    designation_id: "4",
    department: "",
    surname: "Etukudoh",
    firstname: "Patience",
    middlename: "Matilda",
    username: "anthonypatience936@gmail.com",
    email: "anthonypatience936@gmail.com",
    phoneno: "7038404270",
    address: "",
    image: null,
    class_assigned: null,
    sub_class: null,
    signature: null,
    password: "$2y$10$gU7567xqkoyZW1.mkPcWie116aI0Cnu.dM4hQ9Cl31ad3V1Pi8xPy",
    pass_word: "12345678",
    status: "Active",
    created_at: null,
    updated_at: null,
  },
  {
    id: "29",
    sch_id: "SCHMATE/732207",
    campus: "Early Spring Elementary School",
    designation_id: "4",
    department: "",
    surname: "ADEBAYO",
    firstname: "ABOSEDE",
    middlename: "ESTHER",
    username: "",
    email: "",
    phoneno: "7064516292",
    address: "",
    image: null,
    class_assigned: null,
    sub_class: null,
    signature: null,
    password: "$2y$10$gU7567xqkoyZW1.mkPcWie116aI0Cnu.dM4hQ9Cl31ad3V1Pi8xPy",
    pass_word: "12345678",
    status: "Active",
    created_at: null,
    updated_at: null,
  },
  {
    id: "30",
    sch_id: "SCHMATE/732207",
    campus: "Early Spring Elementary School",
    designation_id: "4",
    department: "",
    surname: "Osuji",
    firstname: "Chioma",
    middlename: "Lucy",
    username: "",
    email: "",
    phoneno: "8069836175",
    address: "",
    image: null,
    class_assigned: null,
    sub_class: null,
    signature: null,
    password: "$2y$10$gU7567xqkoyZW1.mkPcWie116aI0Cnu.dM4hQ9Cl31ad3V1Pi8xPy",
    pass_word: "12345678",
    status: "Active",
    created_at: null,
    updated_at: null,
  },
  {
    id: "31",
    sch_id: "SCHMATE/732207",
    campus: "Early Spring Elementary School",
    designation_id: "4",
    department: "",
    surname: "Davis",
    firstname: "Ezechinyere",
    middlename: "",
    username: "",
    email: "",
    phoneno: "8102043275",
    address: "",
    image: null,
    class_assigned: null,
    sub_class: null,
    signature: null,
    password: "$2y$10$gU7567xqkoyZW1.mkPcWie116aI0Cnu.dM4hQ9Cl31ad3V1Pi8xPy",
    pass_word: "12345678",
    status: "Active",
    created_at: null,
    updated_at: null,
  },
  {
    id: "32",
    sch_id: "SCHMATE/732207",
    campus: "Early Spring Elementary School",
    designation_id: "4",
    department: "",
    surname: "SHITTU",
    firstname: "MAYOWA",
    middlename: "DANIEL",
    username: "",
    email: "",
    phoneno: "8034389545",
    address: "",
    image: null,
    class_assigned: null,
    sub_class: null,
    signature: null,
    password: "$2y$10$gU7567xqkoyZW1.mkPcWie116aI0Cnu.dM4hQ9Cl31ad3V1Pi8xPy",
    pass_word: "12345678",
    status: "Active",
    created_at: null,
    updated_at: null,
  },
  {
    id: "33",
    sch_id: "SCHMATE/732207",
    campus: "Early Spring Elementary School",
    designation_id: "4",
    department: "",
    surname: "Uche",
    firstname: "Salome",
    middlename: "Chizoba",
    username: "",
    email: "",
    phoneno: "8068320199",
    address: "",
    image: null,
    class_assigned: null,
    sub_class: null,
    signature: null,
    password: "$2y$10$gU7567xqkoyZW1.mkPcWie116aI0Cnu.dM4hQ9Cl31ad3V1Pi8xPy",
    pass_word: "12345678",
    status: "Active",
    created_at: null,
    updated_at: null,
  },
  {
    id: "34",
    sch_id: "SCHMATE/732207",
    campus: "Early Spring Elementary School",
    designation_id: "4",
    department: "",
    surname: "OBI",
    firstname: "CHIDINMA",
    middlename: "MAUREEN",
    username: "maurexchi@gmail.com",
    email: "maurexchi@gmail.com",
    phoneno: "8163188589",
    address: "",
    image: null,
    class_assigned: null,
    sub_class: null,
    signature: null,
    password: "$2y$10$gU7567xqkoyZW1.mkPcWie116aI0Cnu.dM4hQ9Cl31ad3V1Pi8xPy",
    pass_word: "12345678",
    status: "Active",
    created_at: null,
    updated_at: null,
  },
  {
    id: "35",
    sch_id: "SCHMATE/732207",
    campus: "Early Spring Elementary School",
    designation_id: "4",
    department: "Teaching Staff",
    surname: "Akanni",
    firstname: "Joy",
    middlename: "Stephanie",
    username: "joystephanie9@gmail.com",
    email: "joystephanie9@gmail.com",
    phoneno: "2348174582209",
    address: "",
    image: null,
    class_assigned: null,
    sub_class: null,
    signature: null,
    password: "$2y$10$gU7567xqkoyZW1.mkPcWie116aI0Cnu.dM4hQ9Cl31ad3V1Pi8xPy",
    pass_word: "12345678",
    status: "Active",
    created_at: null,
    updated_at: null,
  },
  {
    id: "36",
    sch_id: "SCHMATE/732207",
    campus: "Early Spring Elementary School",
    designation_id: "4",
    department: "Teaching Staff",
    surname: "Kalu",
    firstname: "Chidinma",
    middlename: "Obasi",
    username: "mma4peter@gmail.com",
    email: "mma4peter@gmail.com",
    phoneno: "2348178629350",
    address: "",
    image: null,
    class_assigned: null,
    sub_class: null,
    signature: null,
    password: "$2y$10$gU7567xqkoyZW1.mkPcWie116aI0Cnu.dM4hQ9Cl31ad3V1Pi8xPy",
    pass_word: "12345678",
    status: "Active",
    created_at: null,
    updated_at: null,
  },
  {
    id: "37",
    sch_id: "SCHMATE/732207",
    campus: "Early Spring Elementary School",
    designation_id: "4",
    department: "Teaching Staff",
    surname: "Achonye",
    firstname: "Stellamaris",
    middlename: "",
    username: "nonye.nas@gmail.com",
    email: "nonye.nas@gmail.com",
    phoneno: "2348028646100",
    address: "",
    image: null,
    class_assigned: null,
    sub_class: null,
    signature: null,
    password: "$2y$10$gU7567xqkoyZW1.mkPcWie116aI0Cnu.dM4hQ9Cl31ad3V1Pi8xPy",
    pass_word: "12345678",
    status: "Active",
    created_at: null,
    updated_at: null,
  },
  {
    id: "38",
    sch_id: "SCHMATE/732207",
    campus: "Early Spring Elementary School",
    designation_id: "4",
    department: "Teaching Staff",
    surname: "Austine-Osem",
    firstname: "Tabitha",
    middlename: "Ekiagho",
    username: "goldtab@gmail.com",
    email: "goldtab@gmail.com",
    phoneno: "2348081540042",
    address: "",
    image: null,
    class_assigned: null,
    sub_class: null,
    signature: null,
    password: "$2y$10$gU7567xqkoyZW1.mkPcWie116aI0Cnu.dM4hQ9Cl31ad3V1Pi8xPy",
    pass_word: "12345678",
    status: "Active",
    created_at: null,
    updated_at: null,
  },
  {
    id: "39",
    sch_id: "SCHMATE/732207",
    campus: "Early Spring Elementary School",
    designation_id: "4",
    department: "Teaching Staff",
    surname: "Otse",
    firstname: "Ndidi",
    middlename: "",
    username: "",
    email: "",
    phoneno: "2348182209907",
    address: "",
    image: null,
    class_assigned: null,
    sub_class: null,
    signature: null,
    password: "$2y$10$gU7567xqkoyZW1.mkPcWie116aI0Cnu.dM4hQ9Cl31ad3V1Pi8xPy",
    pass_word: "12345678",
    status: "Active",
    created_at: null,
    updated_at: null,
  },
  {
    id: "40",
    sch_id: "SCHMATE/732207",
    campus: "Early Spring Elementary School",
    designation_id: "4",
    department: "Teaching Staff",
    surname: "Ibeh",
    firstname: "Ogechi",
    middlename: "Edith",
    username: "",
    email: "",
    phoneno: "2349080425323",
    address: "",
    image: null,
    class_assigned: null,
    sub_class: null,
    signature: null,
    password: "$2y$10$gU7567xqkoyZW1.mkPcWie116aI0Cnu.dM4hQ9Cl31ad3V1Pi8xPy",
    pass_word: "12345678",
    status: "Active",
    created_at: null,
    updated_at: null,
  },
  {
    id: "41",
    sch_id: "SCHMATE/732207",
    campus: "Early Spring Elementary School",
    designation_id: "4",
    department: "Teaching Staff",
    surname: "Awaogu",
    firstname: "Pamela",
    middlename: "",
    username: "awaogupamela@gmail.com",
    email: "awaogupamela@gmail.com",
    phoneno: "2349050429125",
    address: "",
    image: null,
    class_assigned: null,
    sub_class: null,
    signature: null,
    password: "$2y$10$gU7567xqkoyZW1.mkPcWie116aI0Cnu.dM4hQ9Cl31ad3V1Pi8xPy",
    pass_word: "12345678",
    status: "Active",
    created_at: null,
    updated_at: null,
  },
  {
    id: "42",
    sch_id: "SCHMATE/732207",
    campus: "Early Spring Elementary School",
    designation_id: "4",
    department: "Teaching Staff",
    surname: "Odu",
    firstname: "Pat",
    middlename: "",
    username: "",
    email: "",
    phoneno: "2348139350288",
    address: "",
    image: null,
    class_assigned: null,
    sub_class: null,
    signature: null,
    password: "$2y$10$gU7567xqkoyZW1.mkPcWie116aI0Cnu.dM4hQ9Cl31ad3V1Pi8xPy",
    pass_word: "12345678",
    status: "Active",
    created_at: null,
    updated_at: null,
  },
  {
    id: "43",
    sch_id: "SCHMATE/732207",
    campus: "Early Spring Elementary School",
    designation_id: "4",
    department: "Teaching Staff",
    surname: "Chinedu-Eluwa",
    firstname: "Chidinma",
    middlename: "Grace",
    username: "chidinmaoguibe48@gmail.com",
    email: "chidinmaoguibe48@gmail.com",
    phoneno: "2348037349422",
    address: "",
    image: null,
    class_assigned: null,
    sub_class: null,
    signature: null,
    password: "$2y$10$gU7567xqkoyZW1.mkPcWie116aI0Cnu.dM4hQ9Cl31ad3V1Pi8xPy",
    pass_word: "12345678",
    status: "Active",
    created_at: null,
    updated_at: null,
  },
  {
    id: "44",
    sch_id: "SCHMATE/732207",
    campus: "Early Spring Elementary School",
    designation_id: "4",
    department: "Teaching Staff",
    surname: "Eziefula",
    firstname: "Ijeoma",
    middlename: "Faith",
    username: "",
    email: "",
    phoneno: "2347033240772",
    address: "",
    image: null,
    class_assigned: null,
    sub_class: null,
    signature: null,
    password: "$2y$10$gU7567xqkoyZW1.mkPcWie116aI0Cnu.dM4hQ9Cl31ad3V1Pi8xPy",
    pass_word: "12345678",
    status: "Active",
    created_at: null,
    updated_at: null,
  },
  {
    id: "45",
    sch_id: "SCHMATE/732207",
    campus: "Early Spring Elementary School",
    designation_id: "4",
    department: "Teaching Staff",
    surname: "Anyanka",
    firstname: "Rosemary",
    middlename: "Ijeoma",
    username: "",
    email: "",
    phoneno: "2347040614336",
    address: "",
    image: null,
    class_assigned: null,
    sub_class: null,
    signature: null,
    password: "$2y$10$gU7567xqkoyZW1.mkPcWie116aI0Cnu.dM4hQ9Cl31ad3V1Pi8xPy",
    pass_word: "12345678",
    status: "Active",
    created_at: null,
    updated_at: null,
  },
  {
    id: "46",
    sch_id: "SCHMATE/732207",
    campus: "Early Spring Elementary School",
    designation_id: "3",
    department: "Teaching Staff",
    surname: "Adesanya",
    firstname: "Deborah",
    middlename: "Olusola",
    username: "debycox007@yahoo.com",
    email: "debycox007@yahoo.com",
    phoneno: "2348034106475",
    address: "",
    image: null,
    class_assigned: null,
    sub_class: null,
    signature: null,
    password: "$2y$10$gU7567xqkoyZW1.mkPcWie116aI0Cnu.dM4hQ9Cl31ad3V1Pi8xPy",
    pass_word: "12345678",
    status: "Active",
    created_at: null,
    updated_at: null,
  },
  {
    id: "47",
    sch_id: "SCHMATE/732207",
    campus: "Early Spring Elementary School",
    designation_id: "3",
    department: "Teaching Staff",
    surname: "Shittu",
    firstname: "Mayowa",
    middlename: "Daniel",
    username: "profmdshittu@gmail.com",
    email: "profmdshittu@gmail.com",
    phoneno: "2348034389545",
    address: "",
    image: null,
    class_assigned: null,
    sub_class: null,
    signature: null,
    password: "$2y$10$gU7567xqkoyZW1.mkPcWie116aI0Cnu.dM4hQ9Cl31ad3V1Pi8xPy",
    pass_word: "12345678",
    status: "Active",
    created_at: null,
    updated_at: null,
  },
  {
    id: "48",
    sch_id: "SCHMATE/732207",
    campus: "Early Spring Elementary School",
    designation_id: "4",
    department: "Teaching Staff",
    surname: "Okeme",
    firstname: "Folashade",
    middlename: "",
    username: "",
    email: "",
    phoneno: "2348181125844",
    address: "",
    image: null,
    class_assigned: null,
    sub_class: null,
    signature: null,
    password: "$2y$10$gU7567xqkoyZW1.mkPcWie116aI0Cnu.dM4hQ9Cl31ad3V1Pi8xPy",
    pass_word: "12345678",
    status: "Active",
    created_at: null,
    updated_at: null,
  },
  {
    id: "49",
    sch_id: "SCHMATE/732207",
    campus: "Early Spring Elementary School",
    designation_id: "4",
    department: "Teaching Staff",
    surname: "Ogbangwo",
    firstname: "Jacob",
    middlename: "",
    username: "",
    email: "",
    phoneno: "2347046483700",
    address: "",
    image: null,
    class_assigned: null,
    sub_class: null,
    signature: null,
    password: "$2y$10$gU7567xqkoyZW1.mkPcWie116aI0Cnu.dM4hQ9Cl31ad3V1Pi8xPy",
    pass_word: "12345678",
    status: "Active",
    created_at: null,
    updated_at: null,
  },
  {
    id: "50",
    sch_id: "SCHMATE/732207",
    campus: "Early Spring Elementary School",
    designation_id: "4",
    department: "Teaching Staff",
    surname: "CHINEDU-ELUWA",
    firstname: "CHIDINMA",
    middlename: "",
    username: "",
    email: "",
    phoneno: "2348037349422",
    address: "",
    image: null,
    class_assigned: null,
    sub_class: null,
    signature: null,
    password: "$2y$10$gU7567xqkoyZW1.mkPcWie116aI0Cnu.dM4hQ9Cl31ad3V1Pi8xPy",
    pass_word: "12345678",
    status: "Active",
    created_at: null,
    updated_at: null,
  },
  {
    id: "51",
    sch_id: "SCHMATE/732207",
    campus: "Early Spring Elementary School",
    designation_id: "4",
    department: "Teaching Staff",
    surname: "Uzochukwu",
    firstname: "Chiwendu",
    middlename: "Mary",
    username: "m.lyte2010@gmail.com",
    email: "m.lyte2010@gmail.com",
    phoneno: "2348081379549",
    address: "",
    image: null,
    class_assigned: null,
    sub_class: null,
    signature: null,
    password: "$2y$10$gU7567xqkoyZW1.mkPcWie116aI0Cnu.dM4hQ9Cl31ad3V1Pi8xPy",
    pass_word: "12345678",
    status: "Active",
    created_at: null,
    updated_at: null,
  },
  {
    id: "52",
    sch_id: "SCHMATE/732207",
    campus: "Early Spring Elementary School",
    designation_id: "4",
    department: "Teaching Staff",
    surname: "Okeke",
    firstname: "Emily",
    middlename: "Oseluonaimen",
    username: "okekeemily82@gmail.com",
    email: "okekeemily82@gmail.com",
    phoneno: "2348033257843",
    address: "",
    image: null,
    class_assigned: null,
    sub_class: null,
    signature: null,
    password: "$2y$10$gU7567xqkoyZW1.mkPcWie116aI0Cnu.dM4hQ9Cl31ad3V1Pi8xPy",
    pass_word: "12345678",
    status: "Active",
    created_at: null,
    updated_at: null,
  },
  {
    id: "53",
    sch_id: "SCHMATE/732207",
    campus: "Early Spring Nursery School",
    designation_id: "1",
    department: "Admin",
    surname: "Nursery",
    firstname: "Admin",
    middlename: "",
    username: "info@earlyspringschools.com",
    email: "info@earlyspringschools.com",
    phoneno: "2348172009473",
    address: "",
    image: null,
    class_assigned: null,
    sub_class: null,
    signature: null,
    password: "$2y$10$gU7567xqkoyZW1.mkPcWie116aI0Cnu.dM4hQ9Cl31ad3V1Pi8xPy",
    pass_word: "12345678",
    status: "Active",
    created_at: null,
    updated_at: null,
  },
  {
    id: "54",
    sch_id: "SCHMATE/732207",
    campus: "Early Spring Nursery School",
    designation_id: "3",
    department: "Teaching Staff",
    surname: "Eluwa",
    firstname: "Peace",
    middlename: "Onome",
    username: "onomeeluwa@gmail.com",
    email: "onomeeluwa@gmail.com",
    phoneno: "2348123782442",
    address: "",
    image: null,
    class_assigned: null,
    sub_class: null,
    signature: null,
    password: "$2y$10$gU7567xqkoyZW1.mkPcWie116aI0Cnu.dM4hQ9Cl31ad3V1Pi8xPy",
    pass_word: "12345678",
    status: "Disabled",
    created_at: null,
    updated_at: null,
  },
  {
    id: "55",
    sch_id: "SCHMATE/732207",
    campus: "Early Spring Nursery School",
    designation_id: "4",
    department: "",
    surname: "Senge",
    firstname: "Holly",
    middlename: "Ayibadoubra",
    username: "",
    email: "",
    phoneno: "8139035662",
    address: "",
    image: null,
    class_assigned: null,
    sub_class: null,
    signature: null,
    password: "$2y$10$gU7567xqkoyZW1.mkPcWie116aI0Cnu.dM4hQ9Cl31ad3V1Pi8xPy",
    pass_word: "12345678",
    status: "Active",
    created_at: null,
    updated_at: null,
  },
  {
    id: "56",
    sch_id: "SCHMATE/732207",
    campus: "Early Spring Nursery School",
    designation_id: "4",
    department: "",
    surname: "Okaka",
    firstname: "Eghosa",
    middlename: "Precious",
    username: "",
    email: "",
    phoneno: "8025970571",
    address: "",
    image: null,
    class_assigned: null,
    sub_class: null,
    signature: null,
    password: "$2y$10$gU7567xqkoyZW1.mkPcWie116aI0Cnu.dM4hQ9Cl31ad3V1Pi8xPy",
    pass_word: "12345678",
    status: "Active",
    created_at: null,
    updated_at: null,
  },
  {
    id: "57",
    sch_id: "SCHMATE/732207",
    campus: "Early Spring Nursery School",
    designation_id: "4",
    department: "",
    surname: "Eluwa",
    firstname: "Onome",
    middlename: "Peace",
    username: "",
    email: "",
    phoneno: "8123782442",
    address: "",
    image: null,
    class_assigned: null,
    sub_class: null,
    signature: null,
    password: "$2y$10$gU7567xqkoyZW1.mkPcWie116aI0Cnu.dM4hQ9Cl31ad3V1Pi8xPy",
    pass_word: "12345678",
    status: "Disabled",
    created_at: null,
    updated_at: null,
  },
  {
    id: "58",
    sch_id: "SCHMATE/732207",
    campus: "Early Spring Nursery School",
    designation_id: "4",
    department: "",
    surname: "Okafor",
    firstname: "Chinwendu",
    middlename: "Kate",
    username: "chidkate@gmail.com",
    email: "chidkate@gmail.com",
    phoneno: "8037794891",
    address: "",
    image: null,
    class_assigned: null,
    sub_class: null,
    signature: null,
    password: "$2y$10$gU7567xqkoyZW1.mkPcWie116aI0Cnu.dM4hQ9Cl31ad3V1Pi8xPy",
    pass_word: "12345678",
    status: "Active",
    created_at: null,
    updated_at: null,
  },
  {
    id: "59",
    sch_id: "SCHMATE/732207",
    campus: "Early Spring Nursery School",
    designation_id: "4",
    department: "",
    surname: "ITEMBA",
    firstname: "ROSE",
    middlename: "CHINELO",
    username: "",
    email: "",
    phoneno: "9031721887",
    address: "",
    image: null,
    class_assigned: null,
    sub_class: null,
    signature: null,
    password: "$2y$10$gU7567xqkoyZW1.mkPcWie116aI0Cnu.dM4hQ9Cl31ad3V1Pi8xPy",
    pass_word: "12345678",
    status: "Active",
    created_at: null,
    updated_at: null,
  },
  {
    id: "60",
    sch_id: "SCHMATE/732207",
    campus: "Early Spring Nursery School",
    designation_id: "4",
    department: "",
    surname: "Bassey",
    firstname: "Elizabeth",
    middlename: "Chinyere",
    username: "",
    email: "",
    phoneno: "8069327232",
    address: "",
    image: null,
    class_assigned: null,
    sub_class: null,
    signature: null,
    password: "$2y$10$gU7567xqkoyZW1.mkPcWie116aI0Cnu.dM4hQ9Cl31ad3V1Pi8xPy",
    pass_word: "12345678",
    status: "Active",
    created_at: null,
    updated_at: null,
  },
  {
    id: "61",
    sch_id: "SCHMATE/732207",
    campus: "Early Spring Nursery School",
    designation_id: "4",
    department: "",
    surname: "Aniagolu",
    firstname: "Eminence",
    middlename: "Chinemerem",
    username: "",
    email: "",
    phoneno: "8165562371",
    address: "",
    image: null,
    class_assigned: null,
    sub_class: null,
    signature: null,
    password: "$2y$10$gU7567xqkoyZW1.mkPcWie116aI0Cnu.dM4hQ9Cl31ad3V1Pi8xPy",
    pass_word: "12345678",
    status: "Active",
    created_at: null,
    updated_at: null,
  },
  {
    id: "62",
    sch_id: "SCHMATE/732207",
    campus: "Early Spring Nursery School",
    designation_id: "4",
    department: "",
    surname: "Yousuo",
    firstname: "Victoria",
    middlename: "Kuronaka",
    username: "",
    email: "",
    phoneno: "7032493424",
    address: "",
    image: null,
    class_assigned: null,
    sub_class: null,
    signature: null,
    password: "$2y$10$gU7567xqkoyZW1.mkPcWie116aI0Cnu.dM4hQ9Cl31ad3V1Pi8xPy",
    pass_word: "12345678",
    status: "Active",
    created_at: null,
    updated_at: null,
  },
  {
    id: "63",
    sch_id: "SCHMATE/732207",
    campus: "Early Spring Nursery School",
    designation_id: "4",
    department: "",
    surname: "ORIAKHI",
    firstname: "ESOHE",
    middlename: "ESE",
    username: "",
    email: "",
    phoneno: "8026505868",
    address: "",
    image: null,
    class_assigned: null,
    sub_class: null,
    signature: null,
    password: "$2y$10$gU7567xqkoyZW1.mkPcWie116aI0Cnu.dM4hQ9Cl31ad3V1Pi8xPy",
    pass_word: "12345678",
    status: "Active",
    created_at: null,
    updated_at: null,
  },
  {
    id: "64",
    sch_id: "SCHMATE/732207",
    campus: "Early Spring Nursery School",
    designation_id: "4",
    department: "",
    surname: "Ogbuehi",
    firstname: "Barbara",
    middlename: "Nwanneka",
    username: "",
    email: "",
    phoneno: "8183753747",
    address: "",
    image: null,
    class_assigned: null,
    sub_class: null,
    signature: null,
    password: "$2y$10$gU7567xqkoyZW1.mkPcWie116aI0Cnu.dM4hQ9Cl31ad3V1Pi8xPy",
    pass_word: "12345678",
    status: "Active",
    created_at: null,
    updated_at: null,
  },
  {
    id: "65",
    sch_id: "SCHMATE/732207",
    campus: "Early Spring Nursery School",
    designation_id: "4",
    department: "",
    surname: "Bassey",
    firstname: "Mercy",
    middlename: "Ngozi",
    username: "",
    email: "",
    phoneno: "8177119540",
    address: "",
    image: null,
    class_assigned: null,
    sub_class: null,
    signature: null,
    password: "$2y$10$gU7567xqkoyZW1.mkPcWie116aI0Cnu.dM4hQ9Cl31ad3V1Pi8xPy",
    pass_word: "12345678",
    status: "Active",
    created_at: null,
    updated_at: null,
  },
  {
    id: "66",
    sch_id: "SCHMATE/732207",
    campus: "Early Spring Nursery School",
    designation_id: "4",
    department: "",
    surname: "Adegbiyi",
    firstname: "Anike",
    middlename: "Modupe",
    username: "anikeadegbiyi@gmail.com",
    email: "anikeadegbiyi@gmail.com",
    phoneno: "2348063080353",
    address: "",
    image: null,
    class_assigned: null,
    sub_class: null,
    signature: null,
    password: "$2y$10$gU7567xqkoyZW1.mkPcWie116aI0Cnu.dM4hQ9Cl31ad3V1Pi8xPy",
    pass_word: "12345678",
    status: "Active",
    created_at: null,
    updated_at: null,
  },
  {
    id: "67",
    sch_id: "SCHMATE/732207",
    campus: "Early Spring Nursery School",
    designation_id: "4",
    department: "",
    surname: "ABEL-ADEMILOYE",
    firstname: "OGOOLUWAKEMI",
    middlename: "PETRA",
    username: "",
    email: "",
    phoneno: "2348148652908",
    address: "",
    image: null,
    class_assigned: null,
    sub_class: null,
    signature: null,
    password: "$2y$10$gU7567xqkoyZW1.mkPcWie116aI0Cnu.dM4hQ9Cl31ad3V1Pi8xPy",
    pass_word: "12345678",
    status: "Active",
    created_at: null,
    updated_at: null,
  },
  {
    id: "68",
    sch_id: "SCHMATE/732207",
    campus: "Early Spring Nursery School",
    designation_id: "4",
    department: "",
    surname: "Ifeanyi-Uzomah",
    firstname: "Nneamaka",
    middlename: "Patience",
    username: "",
    email: "",
    phoneno: "8139342140",
    address: "",
    image: null,
    class_assigned: null,
    sub_class: null,
    signature: null,
    password: "$2y$10$gU7567xqkoyZW1.mkPcWie116aI0Cnu.dM4hQ9Cl31ad3V1Pi8xPy",
    pass_word: "12345678",
    status: "Active",
    created_at: null,
    updated_at: null,
  },
  {
    id: "69",
    sch_id: "SCHMATE/732207",
    campus: "Early Spring Nursery School",
    designation_id: "4",
    department: "",
    surname: "UDOKWU",
    firstname: "SONIA",
    middlename: "CHIOMA",
    username: "soniachiomaudokwu0@gmail.com",
    email: "soniachiomaudokwu0@gmail.com",
    phoneno: "8068896493",
    address: "",
    image: null,
    class_assigned: null,
    sub_class: null,
    signature: null,
    password: "$2y$10$gU7567xqkoyZW1.mkPcWie116aI0Cnu.dM4hQ9Cl31ad3V1Pi8xPy",
    pass_word: "12345678",
    status: "Active",
    created_at: null,
    updated_at: null,
  },
  {
    id: "70",
    sch_id: "SCHMATE/732207",
    campus: "Early Spring Nursery School",
    designation_id: "4",
    department: "",
    surname: "Ibe",
    firstname: "Chidinma",
    middlename: "Lynda",
    username: "chisbella@yahoo.com",
    email: "chisbella@yahoo.com",
    phoneno: "8034446789",
    address: "",
    image: null,
    class_assigned: null,
    sub_class: null,
    signature: null,
    password: "$2y$10$gU7567xqkoyZW1.mkPcWie116aI0Cnu.dM4hQ9Cl31ad3V1Pi8xPy",
    pass_word: "12345678",
    status: "Active",
    created_at: null,
    updated_at: null,
  },
  {
    id: "71",
    sch_id: "SCHMATE/732207",
    campus: "Early Spring Nursery School",
    designation_id: "4",
    department: "",
    surname: "Ogbonna",
    firstname: "Ita",
    middlename: "Uchechukwu",
    username: "",
    email: "",
    phoneno: "8086613334",
    address: "",
    image: null,
    class_assigned: null,
    sub_class: null,
    signature: null,
    password: "$2y$10$gU7567xqkoyZW1.mkPcWie116aI0Cnu.dM4hQ9Cl31ad3V1Pi8xPy",
    pass_word: "12345678",
    status: "Active",
    created_at: null,
    updated_at: null,
  },
  {
    id: "72",
    sch_id: "SCHMATE/732207",
    campus: "Early Spring Nursery School",
    designation_id: "4",
    department: "",
    surname: "Anih",
    firstname: "Ngozi",
    middlename: "Esther",
    username: "",
    email: "",
    phoneno: "8032292159",
    address: "",
    image: null,
    class_assigned: null,
    sub_class: null,
    signature: null,
    password: "$2y$10$gU7567xqkoyZW1.mkPcWie116aI0Cnu.dM4hQ9Cl31ad3V1Pi8xPy",
    pass_word: "12345678",
    status: "Active",
    created_at: null,
    updated_at: null,
  },
  {
    id: "73",
    sch_id: "SCHMATE/732207",
    campus: "Early Spring Nursery School",
    designation_id: "4",
    department: "",
    surname: "Nwafor",
    firstname: "Oluchi",
    middlename: "Salome",
    username: "salomeoluchi204@gmail.com",
    email: "salomeoluchi204@gmail.com",
    phoneno: "8160323568",
    address: "",
    image: null,
    class_assigned: null,
    sub_class: null,
    signature: null,
    password: "$2y$10$gU7567xqkoyZW1.mkPcWie116aI0Cnu.dM4hQ9Cl31ad3V1Pi8xPy",
    pass_word: "12345678",
    status: "Active",
    created_at: null,
    updated_at: null,
  },
  {
    id: "74",
    sch_id: "SCHMATE/732207",
    campus: "Early Spring Nursery School",
    designation_id: "3",
    department: "",
    surname: "ADESANYA",
    firstname: "DEBORAH",
    middlename: "OLUSOLA",
    username: "",
    email: "",
    phoneno: "8034106475",
    address: "",
    image: null,
    class_assigned: null,
    sub_class: null,
    signature: null,
    password: "$2y$10$gU7567xqkoyZW1.mkPcWie116aI0Cnu.dM4hQ9Cl31ad3V1Pi8xPy",
    pass_word: "12345678",
    status: "Active",
    created_at: null,
    updated_at: null,
  },
  {
    id: "75",
    sch_id: "SCHMATE/732207",
    campus: "Early Spring Nursery School",
    designation_id: "4",
    department: "Teaching Staff",
    surname: "Ukadugwu",
    firstname: "Somtochukwu",
    middlename: "",
    username: "ukasomtochukwu@gmail.com",
    email: "ukasomtochukwu@gmail.com",
    phoneno: "2348144955797",
    address: "",
    image: null,
    class_assigned: null,
    sub_class: null,
    signature: null,
    password: "$2y$10$gU7567xqkoyZW1.mkPcWie116aI0Cnu.dM4hQ9Cl31ad3V1Pi8xPy",
    pass_word: "12345678",
    status: "Active",
    created_at: null,
    updated_at: null,
  },
  {
    id: "76",
    sch_id: "SCHMATE/732207",
    campus: "Early Spring Nursery School",
    designation_id: "4",
    department: "Teaching Staff",
    surname: "Ezekafor",
    firstname: "Kosiso",
    middlename: "",
    username: "",
    email: "",
    phoneno: "2349072832838",
    address: "",
    image: null,
    class_assigned: null,
    sub_class: null,
    signature: null,
    password: "$2y$10$gU7567xqkoyZW1.mkPcWie116aI0Cnu.dM4hQ9Cl31ad3V1Pi8xPy",
    pass_word: "12345678",
    status: "Active",
    created_at: null,
    updated_at: null,
  },
  {
    id: "77",
    sch_id: "SCHMATE/732207",
    campus: "Early Spring Nursery School",
    designation_id: "4",
    department: "Teaching Staff",
    surname: "Okeme",
    firstname: "Folashade",
    middlename: "",
    username: "",
    email: "",
    phoneno: "2348181125844",
    address: "",
    image: null,
    class_assigned: null,
    sub_class: null,
    signature: null,
    password: "$2y$10$gU7567xqkoyZW1.mkPcWie116aI0Cnu.dM4hQ9Cl31ad3V1Pi8xPy",
    pass_word: "12345678",
    status: "Active",
    created_at: null,
    updated_at: null,
  },
  {
    id: "78",
    sch_id: "SCHMATE/732207",
    campus: "Early Spring Nursery School",
    designation_id: "4",
    department: "Teaching Staff",
    surname: "Ogbonna",
    firstname: "Grace",
    middlename: "Eno",
    username: "",
    email: "",
    phoneno: "2348093529506",
    address: "",
    image: null,
    class_assigned: null,
    sub_class: null,
    signature: null,
    password: "$2y$10$gU7567xqkoyZW1.mkPcWie116aI0Cnu.dM4hQ9Cl31ad3V1Pi8xPy",
    pass_word: "12345678",
    status: "Active",
    created_at: null,
    updated_at: null,
  },
  {
    id: "79",
    sch_id: "SCHMATE/732207",
    campus: "Early Spring Nursery School",
    designation_id: "4",
    department: "Teaching Staff",
    surname: "Kolawole",
    firstname: "Funmilayo",
    middlename: "Gloria",
    username: "funmygracious@gmail.com",
    email: "funmygracious@gmail.com",
    phoneno: "2347038608530",
    address: "",
    image: null,
    class_assigned: null,
    sub_class: null,
    signature: null,
    password: "$2y$10$gU7567xqkoyZW1.mkPcWie116aI0Cnu.dM4hQ9Cl31ad3V1Pi8xPy",
    pass_word: "12345678",
    status: "Active",
    created_at: null,
    updated_at: null,
  },
  {
    id: "80",
    sch_id: "SCHMATE/732207",
    campus: "Early Spring Nursery School",
    designation_id: "4",
    department: "Teaching Staff",
    surname: "Chinedum",
    firstname: "Esther",
    middlename: "",
    username: "estheragwuu@gmail.com",
    email: "estheragwuu@gmail.com",
    phoneno: "2348063154010",
    address: "",
    image: null,
    class_assigned: null,
    sub_class: null,
    signature: null,
    password: "$2y$10$gU7567xqkoyZW1.mkPcWie116aI0Cnu.dM4hQ9Cl31ad3V1Pi8xPy",
    pass_word: "12345678",
    status: "Active",
    created_at: null,
    updated_at: null,
  },
  {
    id: "81",
    sch_id: "SCHMATE/732207",
    campus: "Early Spring Nursery School",
    designation_id: "4",
    department: "Teaching Staff",
    surname: "James",
    firstname: "Beauty",
    middlename: "",
    username: "",
    email: "",
    phoneno: "2347069307436",
    address: "",
    image: null,
    class_assigned: null,
    sub_class: null,
    signature: null,
    password: "$2y$10$gU7567xqkoyZW1.mkPcWie116aI0Cnu.dM4hQ9Cl31ad3V1Pi8xPy",
    pass_word: "12345678",
    status: "Active",
    created_at: null,
    updated_at: null,
  },
  {
    id: "82",
    sch_id: "SCHMATE/732207",
    campus: "Early Spring Nursery School",
    designation_id: "4",
    department: "Teaching Staff",
    surname: "Effiong",
    firstname: "Matilda",
    middlename: "",
    username: "",
    email: "",
    phoneno: "2348183901902",
    address: "",
    image: null,
    class_assigned: null,
    sub_class: null,
    signature: null,
    password: "$2y$10$gU7567xqkoyZW1.mkPcWie116aI0Cnu.dM4hQ9Cl31ad3V1Pi8xPy",
    pass_word: "12345678",
    status: "Active",
    created_at: null,
    updated_at: null,
  },
  {
    id: "83",
    sch_id: "SCHMATE/732207",
    campus: "Early Spring Nursery School",
    designation_id: "3",
    department: "Teaching Staff",
    surname: "ELUWA",
    firstname: "ONOME",
    middlename: "PEACE",
    username: "onomeeluwa@gmail.com",
    email: "onomeeluwa@gmail.com",
    phoneno: "2348067832797",
    address: "",
    image: null,
    class_assigned: null,
    sub_class: null,
    signature: null,
    password: "$2y$10$gU7567xqkoyZW1.mkPcWie116aI0Cnu.dM4hQ9Cl31ad3V1Pi8xPy",
    pass_word: "12345678",
    status: "Disabled",
    created_at: null,
    updated_at: null,
  },
  {
    id: "84",
    sch_id: "SCHMATE/732207",
    campus: "Early Spring Nursery School",
    designation_id: "4",
    department: "Teaching Staff",
    surname: "Joseph",
    firstname: "Regina",
    middlename: "",
    username: "",
    email: "",
    phoneno: "2348074730023",
    address: "",
    image: null,
    class_assigned: null,
    sub_class: null,
    signature: null,
    password: "$2y$10$gU7567xqkoyZW1.mkPcWie116aI0Cnu.dM4hQ9Cl31ad3V1Pi8xPy",
    pass_word: "12345678",
    status: "Active",
    created_at: null,
    updated_at: null,
  },
  {
    id: "85",
    sch_id: "SCHMATE/732207",
    campus: "Early Spring Nursery School",
    designation_id: "4",
    department: "Teaching Staff",
    surname: "Adegbiyi",
    firstname: "Anike",
    middlename: "",
    username: "",
    email: "",
    phoneno: "2348063080353",
    address: "",
    image: null,
    class_assigned: null,
    sub_class: null,
    signature: null,
    password: "$2y$10$gU7567xqkoyZW1.mkPcWie116aI0Cnu.dM4hQ9Cl31ad3V1Pi8xPy",
    pass_word: "12345678",
    status: "Active",
    created_at: null,
    updated_at: null,
  },
  {
    id: "86",
    sch_id: "SCHMATE/732207",
    campus: "Early Spring Nursery School",
    designation_id: "4",
    department: "Teaching Staff",
    surname: "Antiga",
    firstname: "Affiong",
    middlename: "",
    username: "",
    email: "",
    phoneno: "2348164428840",
    address: "",
    image: null,
    class_assigned: null,
    sub_class: null,
    signature: null,
    password: "$2y$10$gU7567xqkoyZW1.mkPcWie116aI0Cnu.dM4hQ9Cl31ad3V1Pi8xPy",
    pass_word: "12345678",
    status: "Active",
    created_at: null,
    updated_at: null,
  },
  {
    id: "87",
    sch_id: "SCHMATE/732207",
    campus: "Early Spring Nursery School",
    designation_id: "4",
    department: "Teaching Staff",
    surname: "Regina",
    firstname: "O",
    middlename: "Joseph",
    username: "",
    email: "",
    phoneno: "2347033344650",
    address: "",
    image: null,
    class_assigned: null,
    sub_class: null,
    signature: null,
    password: "$2y$10$gU7567xqkoyZW1.mkPcWie116aI0Cnu.dM4hQ9Cl31ad3V1Pi8xPy",
    pass_word: "12345678",
    status: "Active",
    created_at: null,
    updated_at: null,
  },
  {
    id: "88",
    sch_id: "SCHMATE/732207",
    campus: "Early Spring Nursery School",
    designation_id: "3",
    department: "Teaching Staff",
    surname: "OGBONNA",
    firstname: "GRACE",
    middlename: "ENO",
    username: "graceikang@gmail.com",
    email: "graceikang@gmail.com",
    phoneno: "2348093529506",
    address: "",
    image: null,
    class_assigned: null,
    sub_class: null,
    signature: null,
    password: "$2y$10$gU7567xqkoyZW1.mkPcWie116aI0Cnu.dM4hQ9Cl31ad3V1Pi8xPy",
    pass_word: "12345678",
    status: "Active",
    created_at: null,
    updated_at: null,
  },
  {
    id: "89",
    sch_id: "SCHMATE/732207",
    campus: "Early Spring Nursery School",
    designation_id: "3",
    department: "Teaching Staff",
    surname: "OGBONNA",
    firstname: "GRACE",
    middlename: "ENO",
    username: "graceikang@gmail.com",
    email: "graceikang@gmail.com",
    phoneno: "2348093529506",
    address: "",
    image: null,
    class_assigned: null,
    sub_class: null,
    signature: null,
    password: "$2y$10$gU7567xqkoyZW1.mkPcWie116aI0Cnu.dM4hQ9Cl31ad3V1Pi8xPy",
    pass_word: "12345678",
    status: "Active",
    created_at: null,
    updated_at: null,
  },
  {
    id: "90",
    sch_id: "SCHMATE/732207",
    campus: "Early Spring Nursery School",
    designation_id: "3",
    department: "Teaching Staff",
    surname: "OGBONNA",
    firstname: "GRACE",
    middlename: "ENO",
    username: "graceikang@gmail.com",
    email: "graceikang@gmail.com",
    phoneno: "2348093529506",
    address: "",
    image: null,
    class_assigned: null,
    sub_class: null,
    signature: null,
    password: "$2y$10$gU7567xqkoyZW1.mkPcWie116aI0Cnu.dM4hQ9Cl31ad3V1Pi8xPy",
    pass_word: "12345678",
    status: "Active",
    created_at: null,
    updated_at: null,
  },
  {
    id: "91",
    sch_id: "SCHMATE/732207",
    campus: "Early Spring Nursery School",
    designation_id: "3",
    department: "Teaching Staff",
    surname: "OGBONNA",
    firstname: "GRACE",
    middlename: "ENO",
    username: "graceikang@gmail.com",
    email: "graceikang@gmail.com",
    phoneno: "2348093529506",
    address: "",
    image: null,
    class_assigned: null,
    sub_class: null,
    signature: null,
    password: "$2y$10$gU7567xqkoyZW1.mkPcWie116aI0Cnu.dM4hQ9Cl31ad3V1Pi8xPy",
    pass_word: "12345678",
    status: "Active",
    created_at: null,
    updated_at: null,
  },
  {
    id: "92",
    sch_id: "SCHMATE/732207",
    campus: "Early Spring Nursery School",
    designation_id: "3",
    department: "None Teaching Staff",
    surname: "ORIAKHI",
    firstname: "ESE",
    middlename: "",
    username: "",
    email: "",
    phoneno: "234908000000",
    address: "",
    image: null,
    class_assigned: null,
    sub_class: null,
    signature: null,
    password: "$2y$10$gU7567xqkoyZW1.mkPcWie116aI0Cnu.dM4hQ9Cl31ad3V1Pi8xPy",
    pass_word: "12345678",
    status: "Active",
    created_at: null,
    updated_at: null,
  },
  {
    id: "93",
    sch_id: "SCHMATE/732207",
    campus: "Early Spring Nursery School",
    designation_id: "4",
    department: "Teaching Staff",
    surname: "Madumelu",
    firstname: "Chika",
    middlename: "Lilian",
    username: "",
    email: "",
    phoneno: "2347034538124",
    address: "",
    image: null,
    class_assigned: null,
    sub_class: null,
    signature: null,
    password: "$2y$10$gU7567xqkoyZW1.mkPcWie116aI0Cnu.dM4hQ9Cl31ad3V1Pi8xPy",
    pass_word: "12345678",
    status: "Active",
    created_at: null,
    updated_at: null,
  },
  {
    id: "94",
    sch_id: "SCHMATE/732207",
    campus: "Early Spring Nursery School",
    designation_id: "4",
    department: "Teaching Staff",
    surname: "Nneamaka",
    firstname: "Patience",
    middlename: "Ifeanyi -Uzoma",
    username: "",
    email: "",
    phoneno: "2348139342140",
    address: "",
    image: null,
    class_assigned: null,
    sub_class: null,
    signature: null,
    password: "$2y$10$gU7567xqkoyZW1.mkPcWie116aI0Cnu.dM4hQ9Cl31ad3V1Pi8xPy",
    pass_word: "12345678",
    status: "Active",
    created_at: null,
    updated_at: null,
  },
  {
    id: "95",
    sch_id: "SCHMATE/732207",
    campus: "Early Spring Nursery School",
    designation_id: "4",
    department: "Teaching Staff",
    surname: "Oletubo",
    firstname: "Rita",
    middlename: "",
    username: "",
    email: "",
    phoneno: "2348163800339",
    address: "",
    image: null,
    class_assigned: null,
    sub_class: null,
    signature: null,
    password: "$2y$10$gU7567xqkoyZW1.mkPcWie116aI0Cnu.dM4hQ9Cl31ad3V1Pi8xPy",
    pass_word: "12345678",
    status: "Active",
    created_at: null,
    updated_at: null,
  },
  {
    id: "96",
    sch_id: "SCHMATE/732207",
    campus: "Early Spring Nursery School",
    designation_id: "4",
    department: "Teaching Staff",
    surname: "Okafor",
    firstname: "Stella",
    middlename: "",
    username: "",
    email: "",
    phoneno: "2347084937767",
    address: "",
    image: null,
    class_assigned: null,
    sub_class: null,
    signature: null,
    password: "$2y$10$gU7567xqkoyZW1.mkPcWie116aI0Cnu.dM4hQ9Cl31ad3V1Pi8xPy",
    pass_word: "12345678",
    status: "Active",
    created_at: null,
    updated_at: null,
  },
  {
    id: "97",
    sch_id: "SCHMATE/732207",
    campus: "Early Spring Nursery School",
    designation_id: "4",
    department: "Teaching Staff",
    surname: "Okorie",
    firstname: "Juliet",
    middlename: "P.",
    username: "Prepre3140@gmail.com",
    email: "Prepre3140@gmail.com",
    phoneno: "2347035272412",
    address: "",
    image: null,
    class_assigned: null,
    sub_class: null,
    signature: null,
    password: "$2y$10$gU7567xqkoyZW1.mkPcWie116aI0Cnu.dM4hQ9Cl31ad3V1Pi8xPy",
    pass_word: "12345678",
    status: "Active",
    created_at: null,
    updated_at: null,
  },
  {
    id: "98",
    sch_id: "SCHMATE/732207",
    campus: "Early Spring Nursery School",
    designation_id: "4",
    department: "Teaching Staff",
    surname: "Davidson",
    firstname: "Nkiruka",
    middlename: "Cynthia",
    username: "davidsonnkiruka@gmail.com",
    email: "davidsonnkiruka@gmail.com",
    phoneno: "2348033655430",
    address: "",
    image: null,
    class_assigned: null,
    sub_class: null,
    signature: null,
    password: "$2y$10$gU7567xqkoyZW1.mkPcWie116aI0Cnu.dM4hQ9Cl31ad3V1Pi8xPy",
    pass_word: "12345678",
    status: "Active",
    created_at: null,
    updated_at: null,
  },
  {
    id: "99",
    sch_id: "SCHMATE/732207",
    campus: "Early Spring Nursery School",
    designation_id: "4",
    department: "Teaching Staff",
    surname: "Madumelu",
    firstname: "Chika",
    middlename: "",
    username: "",
    email: "",
    phoneno: "2347034531824",
    address: "",
    image: null,
    class_assigned: null,
    sub_class: null,
    signature: null,
    password: "$2y$10$gU7567xqkoyZW1.mkPcWie116aI0Cnu.dM4hQ9Cl31ad3V1Pi8xPy",
    pass_word: "12345678",
    status: "Active",
    created_at: null,
    updated_at: null,
  },
  {
    id: "100",
    sch_id: "SCHMATE/732207",
    campus: "Early Spring Nursery School",
    designation_id: "4",
    department: "Teaching Staff",
    surname: "Mercy",
    firstname: "George",
    middlename: "",
    username: "",
    email: "",
    phoneno: "2349034939747",
    address: "",
    image: null,
    class_assigned: null,
    sub_class: null,
    signature: null,
    password: "$2y$10$gU7567xqkoyZW1.mkPcWie116aI0Cnu.dM4hQ9Cl31ad3V1Pi8xPy",
    pass_word: "12345678",
    status: "Active",
    created_at: null,
    updated_at: null,
  },
  {
    id: "101",
    sch_id: "SCHMATE/732207",
    campus: "Early Spring College",
    designation_id: "1",
    department: "Admin",
    surname: "College",
    firstname: "Admin",
    middlename: "",
    username: "info@earlyspringschools.com",
    email: "info@earlyspringschools.com",
    phoneno: "2348165777979",
    address: "",
    image: null,
    class_assigned: null,
    sub_class: null,
    signature: null,
    password: "$2y$10$gU7567xqkoyZW1.mkPcWie116aI0Cnu.dM4hQ9Cl31ad3V1Pi8xPy",
    pass_word: "12345678",
    status: "Active",
    created_at: null,
    updated_at: null,
  },
  {
    id: "102",
    sch_id: "SCHMATE/732207",
    campus: "Early Spring College",
    designation_id: "3",
    department: "Teaching Staff",
    surname: "Okeke",
    firstname: "Chidimma",
    middlename: "M C",
    username: "chidimcokeke@gmail.com",
    email: "chidimcokeke@gmail.com",
    phoneno: "2348034305734",
    address: "",
    image: null,
    class_assigned: null,
    sub_class: null,
    signature: null,
    password: "$2y$10$gU7567xqkoyZW1.mkPcWie116aI0Cnu.dM4hQ9Cl31ad3V1Pi8xPy",
    pass_word: "12345678",
    status: "Active",
    created_at: null,
    updated_at: null,
  },
  {
    id: "103",
    sch_id: "SCHMATE/732207",
    campus: "Early Spring College",
    designation_id: "4",
    department: "",
    surname: "Filani",
    firstname: "Augustine",
    middlename: "Rowland",
    username: "",
    email: "",
    phoneno: "8068047493",
    address: "",
    image: null,
    class_assigned: null,
    sub_class: null,
    signature: null,
    password: "$2y$10$gU7567xqkoyZW1.mkPcWie116aI0Cnu.dM4hQ9Cl31ad3V1Pi8xPy",
    pass_word: "12345678",
    status: "Active",
    created_at: null,
    updated_at: null,
  },
  {
    id: "104",
    sch_id: "SCHMATE/732207",
    campus: "Early Spring College",
    designation_id: "4",
    department: "",
    surname: "EZEOBIORA",
    firstname: "CHISOM",
    middlename: "ODINAKA",
    username: "",
    email: "",
    phoneno: "8133190252",
    address: "",
    image: null,
    class_assigned: null,
    sub_class: null,
    signature: null,
    password: "$2y$10$gU7567xqkoyZW1.mkPcWie116aI0Cnu.dM4hQ9Cl31ad3V1Pi8xPy",
    pass_word: "12345678",
    status: "Active",
    created_at: null,
    updated_at: null,
  },
  {
    id: "105",
    sch_id: "SCHMATE/732207",
    campus: "Early Spring College",
    designation_id: "4",
    department: "",
    surname: "Oduwole",
    firstname: "Bukola",
    middlename: "Margaret",
    username: "",
    email: "",
    phoneno: "9053625596",
    address: "",
    image: null,
    class_assigned: null,
    sub_class: null,
    signature: null,
    password: "$2y$10$gU7567xqkoyZW1.mkPcWie116aI0Cnu.dM4hQ9Cl31ad3V1Pi8xPy",
    pass_word: "12345678",
    status: "Active",
    created_at: null,
    updated_at: null,
  },
  {
    id: "106",
    sch_id: "SCHMATE/732207",
    campus: "Early Spring College",
    designation_id: "4",
    department: "",
    surname: "OKEKE",
    firstname: "CHIDIMMA",
    middlename: "MARY-CYNTHIA",
    username: "",
    email: "",
    phoneno: "8034305734",
    address: "",
    image: null,
    class_assigned: null,
    sub_class: null,
    signature: null,
    password: "$2y$10$gU7567xqkoyZW1.mkPcWie116aI0Cnu.dM4hQ9Cl31ad3V1Pi8xPy",
    pass_word: "12345678",
    status: "Active",
    created_at: null,
    updated_at: null,
  },
  {
    id: "107",
    sch_id: "SCHMATE/732207",
    campus: "Early Spring College",
    designation_id: "4",
    department: "",
    surname: "DADA",
    firstname: "OMOTINUOLAJI",
    middlename: "OMOTOYOSI",
    username: "",
    email: "",
    phoneno: "8187064825",
    address: "",
    image: null,
    class_assigned: null,
    sub_class: null,
    signature: null,
    password: "$2y$10$gU7567xqkoyZW1.mkPcWie116aI0Cnu.dM4hQ9Cl31ad3V1Pi8xPy",
    pass_word: "12345678",
    status: "Active",
    created_at: null,
    updated_at: null,
  },
  {
    id: "108",
    sch_id: "SCHMATE/732207",
    campus: "Early Spring College",
    designation_id: "4",
    department: "",
    surname: "Dike",
    firstname: "Ezinne",
    middlename: "Jovita",
    username: "joviclare@gmail.com",
    email: "joviclare@gmail.com",
    phoneno: "7031237061",
    address: "",
    image: null,
    class_assigned: null,
    sub_class: null,
    signature: null,
    password: "$2y$10$gU7567xqkoyZW1.mkPcWie116aI0Cnu.dM4hQ9Cl31ad3V1Pi8xPy",
    pass_word: "12345678",
    status: "Active",
    created_at: null,
    updated_at: null,
  },
  {
    id: "109",
    sch_id: "SCHMATE/732207",
    campus: "Early Spring College",
    designation_id: "4",
    department: "",
    surname: "Ekhator",
    firstname: "Patrick",
    middlename: "Osakpamwan",
    username: "",
    email: "",
    phoneno: "7064393409",
    address: "",
    image: null,
    class_assigned: null,
    sub_class: null,
    signature: null,
    password: "$2y$10$gU7567xqkoyZW1.mkPcWie116aI0Cnu.dM4hQ9Cl31ad3V1Pi8xPy",
    pass_word: "12345678",
    status: "Active",
    created_at: null,
    updated_at: null,
  },
  {
    id: "110",
    sch_id: "SCHMATE/732207",
    campus: "Early Spring College",
    designation_id: "4",
    department: "",
    surname: "Osman",
    firstname: "Isaac",
    middlename: "Oluwafikayo",
    username: "",
    email: "",
    phoneno: "8039440324",
    address: "",
    image: null,
    class_assigned: null,
    sub_class: null,
    signature: null,
    password: "$2y$10$gU7567xqkoyZW1.mkPcWie116aI0Cnu.dM4hQ9Cl31ad3V1Pi8xPy",
    pass_word: "12345678",
    status: "Active",
    created_at: null,
    updated_at: null,
  },
  {
    id: "111",
    sch_id: "SCHMATE/732207",
    campus: "Early Spring College",
    designation_id: "4",
    department: "",
    surname: "Olayimika",
    firstname: "Adebayo",
    middlename: "Olusesan",
    username: "adebayoigcsemaths@gmail.com",
    email: "adebayoigcsemaths@gmail.com",
    phoneno: "7066539953",
    address: "",
    image: null,
    class_assigned: null,
    sub_class: null,
    signature: null,
    password: "$2y$10$gU7567xqkoyZW1.mkPcWie116aI0Cnu.dM4hQ9Cl31ad3V1Pi8xPy",
    pass_word: "12345678",
    status: "Active",
    created_at: null,
    updated_at: null,
  },
  {
    id: "112",
    sch_id: "SCHMATE/732207",
    campus: "Early Spring College",
    designation_id: "4",
    department: "",
    surname: "Silva",
    firstname: "Cynthia",
    middlename: "Adaure",
    username: "reachcyntia@gmail.com",
    email: "reachcyntia@gmail.com",
    phoneno: "8067168602",
    address: "",
    image: null,
    class_assigned: null,
    sub_class: null,
    signature: null,
    password: "$2y$10$gU7567xqkoyZW1.mkPcWie116aI0Cnu.dM4hQ9Cl31ad3V1Pi8xPy",
    pass_word: "12345678",
    status: "Active",
    created_at: null,
    updated_at: null,
  },
  {
    id: "113",
    sch_id: "SCHMATE/732207",
    campus: "Early Spring College",
    designation_id: "4",
    department: "",
    surname: "Omotoyese",
    firstname: "Samson",
    middlename: "Akinloye",
    username: "",
    email: "",
    phoneno: "9032927600",
    address: "",
    image: null,
    class_assigned: null,
    sub_class: null,
    signature: null,
    password: "$2y$10$gU7567xqkoyZW1.mkPcWie116aI0Cnu.dM4hQ9Cl31ad3V1Pi8xPy",
    pass_word: "12345678",
    status: "Disabled",
    created_at: null,
    updated_at: null,
  },
  {
    id: "114",
    sch_id: "SCHMATE/732207",
    campus: "Early Spring College",
    designation_id: "4",
    department: "",
    surname: "Egbo",
    firstname: "Mary",
    middlename: "Chiwendu",
    username: "",
    email: "",
    phoneno: "8060966288",
    address: "",
    image: null,
    class_assigned: null,
    sub_class: null,
    signature: null,
    password: "$2y$10$gU7567xqkoyZW1.mkPcWie116aI0Cnu.dM4hQ9Cl31ad3V1Pi8xPy",
    pass_word: "12345678",
    status: "Active",
    created_at: null,
    updated_at: null,
  },
  {
    id: "115",
    sch_id: "SCHMATE/732207",
    campus: "Early Spring College",
    designation_id: "4",
    department: "",
    surname: "Onuoha",
    firstname: "Darlington",
    middlename: "",
    username: "",
    email: "",
    phoneno: "8030811751",
    address: "",
    image: null,
    class_assigned: null,
    sub_class: null,
    signature: null,
    password: "$2y$10$gU7567xqkoyZW1.mkPcWie116aI0Cnu.dM4hQ9Cl31ad3V1Pi8xPy",
    pass_word: "12345678",
    status: "Disabled",
    created_at: null,
    updated_at: null,
  },
  {
    id: "116",
    sch_id: "SCHMATE/732207",
    campus: "Early Spring College",
    designation_id: "4",
    department: "Teaching Staff",
    surname: "Udofia",
    firstname: "Uduak",
    middlename: "Aniekan",
    username: "Uduaktomudofia@g.mail.com",
    email: "Uduaktomudofia@g.mail.com",
    phoneno: "2347080775281",
    address: "",
    image: null,
    class_assigned: null,
    sub_class: null,
    signature: null,
    password: "$2y$10$gU7567xqkoyZW1.mkPcWie116aI0Cnu.dM4hQ9Cl31ad3V1Pi8xPy",
    pass_word: "12345678",
    status: "Active",
    created_at: null,
    updated_at: null,
  },
  {
    id: "117",
    sch_id: "SCHMATE/732207",
    campus: "Early Spring College",
    designation_id: "4",
    department: "Teaching Staff",
    surname: "Walter",
    firstname: "Tochi",
    middlename: "",
    username: "",
    email: "",
    phoneno: "2348037663885",
    address: "",
    image: null,
    class_assigned: null,
    sub_class: null,
    signature: null,
    password: "$2y$10$gU7567xqkoyZW1.mkPcWie116aI0Cnu.dM4hQ9Cl31ad3V1Pi8xPy",
    pass_word: "12345678",
    status: "Active",
    created_at: null,
    updated_at: null,
  },
  {
    id: "118",
    sch_id: "SCHMATE/732207",
    campus: "Early Spring College",
    designation_id: "4",
    department: "Teaching Staff",
    surname: "Ngwu",
    firstname: "Ngozi",
    middlename: "",
    username: "",
    email: "",
    phoneno: "2348050205873",
    address: "",
    image: null,
    class_assigned: null,
    sub_class: null,
    signature: null,
    password: "$2y$10$gU7567xqkoyZW1.mkPcWie116aI0Cnu.dM4hQ9Cl31ad3V1Pi8xPy",
    pass_word: "12345678",
    status: "Active",
    created_at: null,
    updated_at: null,
  },
  {
    id: "119",
    sch_id: "SCHMATE/732207",
    campus: "Early Spring College",
    designation_id: "4",
    department: "Teaching Staff",
    surname: "Oluyede",
    firstname: "Chioma",
    middlename: "",
    username: "akpatichioma2015@gmail.com",
    email: "akpatichioma2015@gmail.com",
    phoneno: "2348133183573",
    address: "",
    image: null,
    class_assigned: null,
    sub_class: null,
    signature: null,
    password: "$2y$10$gU7567xqkoyZW1.mkPcWie116aI0Cnu.dM4hQ9Cl31ad3V1Pi8xPy",
    pass_word: "12345678",
    status: "Active",
    created_at: null,
    updated_at: null,
  },
  {
    id: "120",
    sch_id: "SCHMATE/732207",
    campus: "Early Spring College",
    designation_id: "4",
    department: "Teaching Staff",
    surname: "Omokanye",
    firstname: "Owolabi",
    middlename: "Akintomiwa",
    username: "omokanyeakintomiwa@gmail.com",
    email: "omokanyeakintomiwa@gmail.com",
    phoneno: "2347062789439",
    address: "",
    image: null,
    class_assigned: null,
    sub_class: null,
    signature: null,
    password: "$2y$10$gU7567xqkoyZW1.mkPcWie116aI0Cnu.dM4hQ9Cl31ad3V1Pi8xPy",
    pass_word: "12345678",
    status: "Active",
    created_at: null,
    updated_at: null,
  },
  {
    id: "121",
    sch_id: "SCHMATE/732207",
    campus: "Early Spring College",
    designation_id: "4",
    department: "Teaching Staff",
    surname: "Alaiyemola",
    firstname: "Olajide",
    middlename: "Olasunkanmi",
    username: "alaiyemolaolajide@gmail.com",
    email: "alaiyemolaolajide@gmail.com",
    phoneno: "2347030485593",
    address: "",
    image: null,
    class_assigned: null,
    sub_class: null,
    signature: null,
    password: "$2y$10$gU7567xqkoyZW1.mkPcWie116aI0Cnu.dM4hQ9Cl31ad3V1Pi8xPy",
    pass_word: "12345678",
    status: "Active",
    created_at: null,
    updated_at: null,
  },
  {
    id: "122",
    sch_id: "SCHMATE/732207",
    campus: "Early Spring College",
    designation_id: "4",
    department: "Teaching Staff",
    surname: "Mitchel",
    firstname: "Ifeanyi",
    middlename: "Emmanuel",
    username: "mitchelemmanuel@yahoo.com",
    email: "mitchelemmanuel@yahoo.com",
    phoneno: "2348024775320",
    address: "",
    image: null,
    class_assigned: null,
    sub_class: null,
    signature: null,
    password: "$2y$10$gU7567xqkoyZW1.mkPcWie116aI0Cnu.dM4hQ9Cl31ad3V1Pi8xPy",
    pass_word: "12345678",
    status: "Active",
    created_at: null,
    updated_at: null,
  },
  {
    id: "123",
    sch_id: "SCHMATE/732207",
    campus: "Early Spring College",
    designation_id: "4",
    department: "Teaching Staff",
    surname: "Alex",
    firstname: "Obiageli",
    middlename: "Augustina",
    username: "obiagelialex20@gmail.com",
    email: "obiagelialex20@gmail.com",
    phoneno: "2348028801423",
    address: "",
    image: null,
    class_assigned: null,
    sub_class: null,
    signature: null,
    password: "$2y$10$gU7567xqkoyZW1.mkPcWie116aI0Cnu.dM4hQ9Cl31ad3V1Pi8xPy",
    pass_word: "12345678",
    status: "Active",
    created_at: null,
    updated_at: null,
  },
  {
    id: "124",
    sch_id: "SCHMATE/732207",
    campus: "Early Spring College",
    designation_id: "4",
    department: "Teaching Staff",
    surname: "Abah",
    firstname: "Emmanuel",
    middlename: "Nduka",
    username: "whypee94@gmail.com",
    email: "whypee94@gmail.com",
    phoneno: "2348061111305",
    address: "",
    image: null,
    class_assigned: null,
    sub_class: null,
    signature: null,
    password: "$2y$10$gU7567xqkoyZW1.mkPcWie116aI0Cnu.dM4hQ9Cl31ad3V1Pi8xPy",
    pass_word: "12345678",
    status: "Active",
    created_at: null,
    updated_at: null,
  },
  {
    id: "125",
    sch_id: "SCHMATE/732207",
    campus: "Early Spring College",
    designation_id: "4",
    department: "Teaching Staff",
    surname: "Adesiyan",
    firstname: "Motunrayo",
    middlename: "Olajumoke",
    username: "",
    email: "",
    phoneno: "2348033931644",
    address: "",
    image: null,
    class_assigned: null,
    sub_class: null,
    signature: null,
    password: "$2y$10$gU7567xqkoyZW1.mkPcWie116aI0Cnu.dM4hQ9Cl31ad3V1Pi8xPy",
    pass_word: "12345678",
    status: "Disabled",
    created_at: null,
    updated_at: null,
  },
  {
    id: "126",
    sch_id: "SCHMATE/732207",
    campus: "Early Spring College",
    designation_id: "4",
    department: "Teaching Staff",
    surname: "Omojowo",
    firstname: "Rotimi",
    middlename: "Hezekiah",
    username: "omojoworotimi@gmail.com",
    email: "omojoworotimi@gmail.com",
    phoneno: "2347036319365",
    address: "",
    image: null,
    class_assigned: null,
    sub_class: null,
    signature: null,
    password: "$2y$10$gU7567xqkoyZW1.mkPcWie116aI0Cnu.dM4hQ9Cl31ad3V1Pi8xPy",
    pass_word: "12345678",
    status: "Active",
    created_at: null,
    updated_at: null,
  },
  {
    id: "127",
    sch_id: "SCHMATE/732207",
    campus: "Early Spring College",
    designation_id: "4",
    department: "Teaching Staff",
    surname: "Abah",
    firstname: "Emmanuel",
    middlename: "",
    username: "",
    email: "",
    phoneno: "2348061111305",
    address: "",
    image: null,
    class_assigned: null,
    sub_class: null,
    signature: null,
    password: "$2y$10$gU7567xqkoyZW1.mkPcWie116aI0Cnu.dM4hQ9Cl31ad3V1Pi8xPy",
    pass_word: "12345678",
    status: "Active",
    created_at: null,
    updated_at: null,
  },
  {
    id: "128",
    sch_id: "SCHMATE/732207",
    campus: "Early Spring College",
    designation_id: "4",
    department: "Teaching Staff",
    surname: "Akatugba",
    firstname: "Nosa",
    middlename: "Peace",
    username: "mails2nosaakatugba@gmail.com",
    email: "mails2nosaakatugba@gmail.com",
    phoneno: "2347031098201",
    address: "",
    image: null,
    class_assigned: null,
    sub_class: null,
    signature: null,
    password: "$2y$10$gU7567xqkoyZW1.mkPcWie116aI0Cnu.dM4hQ9Cl31ad3V1Pi8xPy",
    pass_word: "12345678",
    status: "Active",
    created_at: null,
    updated_at: null,
  },
];
