exports.subjects = [
  {"id":"1","pid":null,"schpid":null,"campus":null,"name":"Mathematics","class":"SS 3"},
  {"id":"2","pid":null,"schpid":null,"campus":null,"name":"English Language","class":"SS 3"},
  {"id":"3","pid":null,"schpid":null,"campus":null,"name":"Physics","class":"SS 3"},
  {"id":"4","pid":null,"schpid":null,"campus":null,"name":"Chemistry","class":"SS 3"},
  {"id":"5","pid":null,"schpid":null,"campus":null,"name":"Biology","class":"SS 3"},
  {"id":"6","pid":null,"schpid":null,"campus":null,"name":"Further Mathematics","class":"SS 3"},
  {"id":"7","pid":null,"schpid":null,"campus":null,"name":"Geography","class":"SS 3"},
  {"id":"8","pid":null,"schpid":null,"campus":null,"name":"Government","class":"SS 3"},
  {"id":"9","pid":null,"schpid":null,"campus":null,"name":"Christian Religious Studies","class":"SS 3"},
  {"id":"10","pid":null,"schpid":null,"campus":null,"name":"Commerce","class":"SS 3"},
  {"id":"11","pid":null,"schpid":null,"campus":null,"name":"Civic Education","class":"SS 3"},
  {"id":"12","pid":null,"schpid":null,"campus":null,"name":"Economics","class":"SS 3"},
  {"id":"13","pid":null,"schpid":null,"campus":null,"name":"Accounting","class":"SS 3"},
  {"id":"14","pid":null,"schpid":null,"campus":null,"name":"Catering Craft","class":"SS 3"},
  {"id":"15","pid":null,"schpid":null,"campus":null,"name":"Food and Nutrition","class":"SS 3"},
  {"id":"16","pid":null,"schpid":null,"campus":null,"name":"Computer Studies","class":"SS 3"},
  {"id":"17","pid":null,"schpid":null,"campus":null,"name":"Data Processing","class":"SS 3"},
  {"id":"18","pid":null,"schpid":null,"campus":null,"name":"French Language","class":"SS 3"},
  {"id":"19","pid":null,"schpid":null,"campus":null,"name":"Literature - in - English","class":"SS 3"},
  {"id":"20","pid":null,"schpid":null,"campus":null,"name":"Leadership and Character Moulding","class":"SS 3"},
  {"id":"21","pid":null,"schpid":null,"campus":null,"name":"Mathematics","class":"JSS 1"},
  {"id":"22","pid":null,"schpid":null,"campus":null,"name":"English Language","class":"JSS 1"},
  {"id":"23","pid":null,"schpid":null,"campus":null,"name":"Basic Science","class":"JSS 1"},
  {"id":"24","pid":null,"schpid":null,"campus":null,"name":"Basic technology","class":"JSS 1"},
  {"id":"25","pid":null,"schpid":null,"campus":null,"name":"Civic Education","class":"JSS 1"},
  {"id":"26","pid":null,"schpid":null,"campus":null,"name":"Social Studies","class":"JSS 1"},
  {"id":"27","pid":null,"schpid":null,"campus":null,"name":"Computer Studies","class":"JSS 1"},
  {"id":"28","pid":null,"schpid":null,"campus":null,"name":"Business Studies ","class":"JSS 1"},
  {"id":"29","pid":null,"schpid":null,"campus":null,"name":"Christian Religious Studies","class":"JSS 1"},
  {"id":"30","pid":null,"schpid":null,"campus":null,"name":"Fine Art","class":"JSS 1"},
  {"id":"31","pid":null,"schpid":null,"campus":null,"name":"Music","class":"JSS 1"},
  {"id":"32","pid":null,"schpid":null,"campus":null,"name":"Physical and Heath Education","class":"JSS 1"},
  {"id":"33","pid":null,"schpid":null,"campus":null,"name":"Igbo Language","class":"JSS 1"},
  {"id":"34","pid":null,"schpid":null,"campus":null,"name":"yoruba Language","class":"JSS 1"},
  {"id":"35","pid":null,"schpid":null,"campus":null,"name":"Agricultural Science","class":"JSS 1"},
  {"id":"36","pid":null,"schpid":null,"campus":null,"name":"Home Economics","class":"JSS 1"},
  {"id":"37","pid":null,"schpid":null,"campus":null,"name":"French Language","class":"JSS 1"},
  {"id":"38","pid":null,"schpid":null,"campus":null,"name":"Leadership and Character Moulding","class":"JSS 1"},
  {"id":"39","pid":null,"schpid":null,"campus":null,"name":"Visual Art","class":"SS 3"}
  ];
